import Head from 'next/head'
import Link from 'next/link'

const Home = () => {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 */}
    </>
  )
}

Home.layout = 'PUBLIC'

export default Home
