import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">AndresMestra</a>
        </h1>
        <Link href="/admin">
          <a>Admin</a>
        </Link>
        <br />
        <Link href="/blog">
          <a>Blog</a>
        </Link>
      </main>
    </div>
  )
}
